#!/usr/bin/env bun
/**
 * Harness Evidence Report Generator
 * 
 * Generates a markdown report of all evidence collected during development.
 * Saved to .harness/evidence/ for CI artifact upload.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { validateCriteria } from './validate.js';

const ROOT = resolve(import.meta.dir, '../../../../');
const EVIDENCE_DIR = resolve(ROOT, '.harness/evidence');

async function generateReport(): Promise<void> {
  mkdirSync(EVIDENCE_DIR, { recursive: true });

  const { passed, failed, total } = await validateCriteria();
  const timestamp = new Date().toISOString();
  const commitSha = process.env.GITHUB_SHA ?? 'local';

  const report = `# Harness Evidence Report

**Generated:** ${timestamp}
**Commit:** ${commitSha}
**Iteration:** ${process.env.HARNESS_ITERATION ?? '1'}

## Summary

| Metric | Value |
|--------|-------|
| Total Criteria | ${total} |
| Passed | ${passed.length} |
| Failed | ${failed.length} |
| Completion | ${Math.round((passed.length / total) * 100)}% |

## Criteria Status

### ✅ Passed (${passed.length})

${passed.map((id) => `- \`${id}\``).join('\n')}

### ❌ Failed (${failed.length})

${failed.length > 0 ? failed.map((id) => `- \`${id}\``).join('\n') : '_None — all criteria met!_'}

## Decisions Log

_Decisions are recorded in the harness state file during development._

## Next Actions

${failed.length > 0 ? failed.map((id) => `- [ ] Address criterion: \`${id}\``).join('\n') : '- [x] All criteria satisfied. Ready for release.'}

---

_This report is auto-generated by the CorrespondOS harness system._
`;

  const reportPath = resolve(EVIDENCE_DIR, `report-${timestamp.split('T')[0]}.md`);
  writeFileSync(reportPath, report);
  console.log(`📋 Evidence report written to: ${reportPath}`);
}

export { generateReport };

if (import.meta.main) {
  await generateReport();
}
